## Day 3 – Data Exploration & Wrangling

In [3]:
import pandas as pd

In [4]:
df = pd.read_excel("/content/HR-Employee-Attrition.xlsx")

## Explore the dataset

In [5]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [6]:
df.tail()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [8]:
df.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,...,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,802.485714,9.192517,2.912925,1.0,1024.865306,2.721769,65.891156,2.729932,2.063946,...,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,403.509100,8.106864,1.024165,0.0,602.024335,1.093082,20.329428,0.711561,1.106940,...,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,491.250000,2.000000,48.000000,2.000000,1.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,802.000000,7.000000,3.000000,1.0,1020.500000,3.000000,66.000000,3.000000,2.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1555.750000,4.000000,83.750000,3.000000,3.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [9]:
df["Attrition"].value_counts()

Attrition
No     1233
Yes     237
Name: count, dtype: int64

## Detect missing values

In [10]:
print(df.isnull().sum())

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

## Create a small practice dataset with missing values

In [11]:
practice = df[["EmployeeNumber", "MonthlyIncome"]].head(10).copy()

In [12]:
practice.loc[0, "MonthlyIncome"] = None

In [13]:
print(practice)

   EmployeeNumber  MonthlyIncome
0               1            NaN
1               2         5130.0
2               4         2090.0
3               5         2909.0
4               7         3468.0
5               8         3068.0
6              10         2670.0
7              11         2693.0
8              12         9526.0
9              13         5237.0

## fillna() – fill missing value with median

In [14]:
practice["MonthlyIncome"] = practice["MonthlyIncome"].fillna(
    practice["MonthlyIncome"].median()
)

In [15]:
print(practice)

   EmployeeNumber  MonthlyIncome
0               1         3068.0
1               2         5130.0
2               4         2090.0
3               5         2909.0
4               7         3468.0
5               8         3068.0
6              10         2670.0
7              11         2693.0
8              12         9526.0
9              13         5237.0

## dropna() – remove rows containing missing values

In [16]:
dropna_example = practice.copy()

In [17]:
dropna_example.loc[1, "MonthlyIncome"] = None

In [18]:
dropna_example = dropna_example.dropna()

In [19]:
print(dropna_example)

   EmployeeNumber  MonthlyIncome
0               1         3068.0
2               4         2090.0
3               5         2909.0
4               7         3468.0
5               8         3068.0
6              10         2670.0
7              11         2693.0
8              12         9526.0
9              13         5237.0

## Merge two DataFrames

In [20]:
employee_info = df[["EmployeeNumber", "Age", "Gender"]].head(10)

In [21]:
income_info = df[["EmployeeNumber", "MonthlyIncome"]].head(10)

In [22]:
merged_df = pd.merge(employee_info, income_info, on="EmployeeNumber", how="inner")

In [23]:
merged_df.head()

   EmployeeNumber  Age  Gender  MonthlyIncome
0               1   41  Female           5993
1               2   49    Male           5130
2               4   37    Male           2090
3               5   33  Female           2909
4               7   27    Male           3468

## Concatenate two DataFrames

In [24]:
part1 = df.head(5)

In [25]:
part2 = df.tail(5)

In [26]:
concat_df = pd.concat([part1, part2], ignore_index=True)

In [27]:
print(concat_df[["EmployeeNumber", "Age", "Attrition"]])

   EmployeeNumber  Age Attrition
0               1   41       Yes
1               2   49        No
2               4   37       Yes
3               5   33        No
4               7   27        No
5            2061   36        No
6            2062   39        No
7            2064   27        No
8            2065   49        No
9            2068   34        No

## Join two DataFrames using EmployeeNumber as index

In [28]:
left = df[["EmployeeNumber", "Age"]].head(10).set_index("EmployeeNumber")

In [29]:
right = df[["EmployeeNumber", "MonthlyIncome"]].head(10).set_index("EmployeeNumber")

In [30]:
joined_df = left.join(right, how="inner")

In [31]:
print(joined_df.head())

                Age  MonthlyIncome
EmployeeNumber
1                41           5993
2                49           5130
4                37           2090
5                33           2909
7                27           3468

## Group by and aggregate

In [32]:
department_summary = df.groupby("Department").agg(
    Average_Income=("MonthlyIncome", "mean"),
    Average_Age=("Age", "mean"),
    Employee_Count=("EmployeeNumber", "count")
).reset_index()

In [33]:
print(department_summary)

               Department  Average_Income  Average_Age  Employee_Count
0         Human Resources     6654.507937    37.809524              63
1  Research & Development     6281.252862    37.042664             961
2                   Sales     6959.172646    36.542601             446

## Another useful grouping

In [34]:
attrition_summary = df.groupby("Attrition").agg(
    Average_Income=("MonthlyIncome", "mean"),
    Average_Age=("Age", "mean"),
    Employee_Count=("EmployeeNumber", "count")
).reset_index()

In [35]:
print(attrition_summary)

  Attrition  Average_Income  Average_Age  Employee_Count
0        No     6832.739659    37.561233            1233
1       Yes     4787.092827    33.607595             237