# Day 7 – Introduction to Web Scraping & AI

In [4]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [5]:
# Fetch HTML content
url = "https://books.toscrape.com/"
response = requests.get(url, timeout=15)

In [6]:
print("Status code:", response.status_code)

Status code: 200

In [7]:
print("Content type:", response.headers.get("content-type"))

Content type: text/html

In [8]:
html_content = response.text

In [9]:
print("HTML characters:", len(html_content))

HTML characters: 51294

In [10]:
print(html_content[:500])

<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="en-us" class="no-js"> <!--<![endif]-->
    <head>
        <title>
    All products | Books to Scrape - Sandbox
</title>

        <meta http-equiv="content-type" content="text/html; charset=UTF-8" /

## AI-assisted code generation with Gemini in Colab

In [11]:
soup = BeautifulSoup(html_content, "html.parser")

books = []

for article in soup.select("article.product_pod"):
    title_tag = article.select_one("h3 a")
    price_tag = article.select_one(".price_color")

    if title_tag and price_tag:
        books.append({
            "BookTitle": title_tag.get("title", title_tag.get_text(strip=True)),
            "PriceText": price_tag.get_text(strip=True)
        })

scraped_books = pd.DataFrame(books)

print(scraped_books.head())
print("\nRows scraped:", len(scraped_books))

                               BookTitle PriceText
0                   A Light in the Attic   Â£51.77
1                     Tipping the Velvet   Â£53.74
2                             Soumission   Â£50.10
3                          Sharp Objects   Â£47.82
4  Sapiens: A Brief History of Humankind   Â£54.23

Rows scraped: 20

In [15]:
scraped_books["Price"] = (
    scraped_books["PriceText"].str.replace("Â", "", regex=False).str.replace("£", "", regex=False).astype(float)
)

In [ ]:
scraped_books.drop(columns=["PriceText"], inplace=True)

In [16]:
scraped_books.head()

                               BookTitle PriceText  Price
0                   A Light in the Attic   Â£51.77  51.77
1                     Tipping the Velvet   Â£53.74  53.74
2                             Soumission   Â£50.10  50.10
3                          Sharp Objects   Â£47.82  47.82
4  Sapiens: A Brief History of Humankind   Â£54.23  54.23

In [17]:
scraped_books.dtypes

BookTitle     object
PriceText     object
Price        float64
dtype: object

In [19]:
hr = pd.read_excel("/content/HR-Employee-Attrition.xlsx")

In [20]:
hr.shape

(1470, 35)

In [21]:
hr.columns.tolist()[:15]

['Age',
 'Attrition',
 'BusinessTravel',
 'DailyRate',
 'Department',
 'DistanceFromHome',
 'Education',
 'EducationField',
 'EmployeeCount',
 'EmployeeNumber',
 'EnvironmentSatisfaction',
 'Gender',
 'HourlyRate',
 'JobInvolvement',
 'JobLevel']

In [22]:
web_features = pd.DataFrame({
    "WebSource": ["Books to Scrape"],
    "ScrapedBookCount": [len(scraped_books)],
    "AverageScrapedPrice": [scraped_books["Price"].mean()],
    "MinimumScrapedPrice": [scraped_books["Price"].min()],
    "MaximumScrapedPrice": [scraped_books["Price"].max()]
})

In [ ]:
print(web_features)

In [23]:
scraped_books.to_csv("scraped_books_day8.csv", index=False)
web_features.to_csv("web_features_day8.csv", index=False)